/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#eae7e9',
        'tertiary-container': '#0f2a1a',
        'inverse-on-surface': '#f3f0f1',
        'tertiary-fixed': '#caead1',
        'on-secondary-container': '#785a1a',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        surface: '#fbf9fa',
        'on-primary-container': '#818d9f',
        error: '#ba1a1a',
        'primary-container': '#1a2634',
        'on-tertiary-fixed-variant': '#314d3a',
        background: '#fbf9fa',
        'surface-container': '#f0edee',
        'on-secondary-fixed': '#261900',
        'on-primary-fixed': '#101c2a',
        secondary: '#775a19',
        outline: '#75777c',
        'on-primary-fixed-variant': '#3c4857',
        'on-background': '#1b1b1d',
        'surface-variant': '#e4e2e3',
        'on-error-container': '#93000a',
        tertiary: '#001408',
        'inverse-surface': '#303031',
        'primary-fixed': '#d7e3f7',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#e9c176',
        'outline-variant': '#c4c6cc',
        'surface-tint': '#535f6f',
        'primary-fixed-dim': '#bbc7da',
        'on-surface-variant': '#44474c',
        'on-tertiary-fixed': '#052011',
        'on-surface': '#1b1b1d',
        'surface-container-low': '#f5f3f4',
        'on-tertiary-container': '#75937d',
        'secondary-container': '#fed488',
        primary: '#05111e',
        'surface-bright': '#fbf9fa',
        'inverse-primary': '#bbc7da',
        'surface-dim': '#dcd9da',
        'surface-container-highest': '#e4e2e3',
        'tertiary-fixed-dim': '#afceb6',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#5d4201',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffdea5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        xl: '96px',
        base: '4px',
        'container-max': '1200px',
        md: '24px',
        lg: '48px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-sm': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'body-md': ['"Public Sans"', 'sans-serif'],
        'label-caps': ['"Public Sans"', 'sans-serif'],
        'body-lg': ['"Public Sans"', 'sans-serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
      },
      fontSize: {
        'headline-sm': ['25px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'headline-md': ['31px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
