export const clientProfiles = [
  {
    slug: 'startup-founders',
    n: '01',
    title: 'Startup Founders',
    subtitle: 'Pre-Launch to Series A',
    challenge: "You're moving fast. Incorporation, GST setup, first hire, fundraising prep. Meanwhile, books are a mess, cap table is unclear, and you don't know if you have 3 months or 3 weeks of runway.",
    whatWeDo: 'End-to-end startup setup from Day 1 through fundraising. We handle: incorporation, GST registration, DPIIT recognition, bookkeeping setup, monthly MIS, financial modeling (5-year), cap table cleanup, due diligence prep, and Virtual CFO support. You get one point of contact (CA Mayank or CA Vivek) who owns your complete financial journey.',
    whyMojaa: "Most CAs are compliance-focused. We're strategy-focused. We think about runway, unit economics, investor expectations, and dilution paths. We don't just file forms; we prepare you for institutional capital.",
    engagement: 'Incorporation + compliance + financial setup (months 1–3) → Monthly MIS + Virtual CFO (months 4+) → Fundraising prep and modeling (months 6–12). SOW-backed, transparent delivery.',
    nextStep: "We'll assess your current stage and build a custom engagement roadmap.",
  },
  {
    slug: 'venture-backed-startups',
    n: '02',
    title: 'Venture-Backed & Scaling Startups',
    subtitle: 'Series A–Series C',
    challenge: "You're raising capital. Due diligence is intense. Investors ask for 50 documents. Your cap table has conflicts from previous rounds. Financial projections don't match actuals. You need clean books, institutional-grade MIS, and cap table clarity, fast.",
    whatWeDo: 'Internal due diligence audit (before investor DD), cap table restructuring, conflict resolution between investor agreements, financial model review, pitch deck financial validation, term sheet financial terms analysis, monthly board-ready reporting, fundraising-specific tax planning (Section 80-IAC tracking, capital gains strategies).',
    whyMojaa: "CA Vivek has M&A and IPO experience. He's been in VC diligence rooms. He knows what investors scrutinize. We flag issues 8 weeks before institutional DD so you can fix them cleanly instead of scrambling during investor meetings.",
    engagement: 'Pre-fundraise audit (4–6 weeks) → Ongoing monthly board reporting → Ongoing tax and cap table management → Series B prep (if raising again).',
    nextStep: "If you're fundraising in the next 6–12 months, let's do a readiness audit.",
  },
  {
    slug: 'growing-smes',
    n: '03',
    title: 'Growing Businesses & SMEs',
    subtitle: '₹50L–₹10Cr Revenue',
    challenge: "You're profitable or close to it. Books are organized but tax planning is reactive. You don't have a CFO but need financial leadership. Audit compliance is a checkbox; financial strategy is missing.",
    whatWeDo: 'Monthly MIS with metrics (not just P&L), Virtual CFO services (fractional leadership), tax planning (salary vs. dividend, Section 80-IAC, capital gains), annual statutory audit, GST and TDS compliance, working capital optimization, financial modeling for expansion decisions.',
    whyMojaa: 'We think like CFOs, not just compliance officers. We help you decide: should you hire, should you spend on marketing, should you retain profit or distribute dividend. We model scenarios so you decide confidently.',
    engagement: 'Monthly retainer combining MIS, Virtual CFO support, and compliance management. Custom to your complexity.',
    nextStep: "If you're doing ₹50L–₹10Cr revenue and want financial clarity, let's discuss.",
  },
  {
    slug: 'nri-investors',
    n: '04',
    title: 'NRI Investors & Founders',
    subtitle: 'Overseas-Based, Investing in India or Earning Indian Income',
    challenge: "You earn foreign income. You're investing in Indian startups. You own property in India. You need FEMA compliance, tax planning across two countries, and capital gains strategy for Indian exits. Your personal CA doesn't understand cross-border complexity.",
    whatWeDo: 'NRI tax filing (ITR as NRI with foreign income optimization), FEMA compliance for startup investments (FC-GPR filing), DTAA benefits claiming, NRE/NRO account structuring, Form 15CA for remittances, capital gains tax on Indian property sale, angel investment compliance, exit strategy tax planning.',
    whyMojaa: "We specialize in NRI taxation. We know FEMA regulations, DTAA treaties, and income tax treatment across India-US/UK/Australia. We don't just file ITR; we optimize cross-border tax position.",
    engagement: 'Annual ITR filing with cross-border tax optimization + quarterly FEMA advisory + exit planning consultations as needed.',
    nextStep: "If you're an NRI with Indian income or investments, let's discuss tax optimization.",
  },
  {
    slug: 'freelancers',
    n: '05',
    title: 'Freelancers & Independent Professionals',
    subtitle: 'Consultants, Coaches, Advisors',
    challenge: "You're self-employed. Income is variable. You're not sure if you should stay as proprietor or incorporate as OPC. You're confused about GST, TDS on payments you receive, and how to file ITR. Compliance feels overwhelming.",
    whatWeDo: 'Entity structuring advice (should you incorporate?), tax filing (ITR-3 or ITR-5), TDS tracking and refund claims, GST registration strategy, ITR optimization to minimize tax, business expense claiming (home office, equipment, subscriptions), advance tax planning.',
    whyMojaa: 'Most CAs treat freelancers as "simple cases." We treat you like a business. We help you structure for tax efficiency, claim all deductions, and avoid compliance nightmares.',
    engagement: 'Annual ITR filing + GST compliance (if applicable) + ad-hoc tax advice on major decisions.',
    nextStep: "If you're earning ₹20L+ annually and unsure about structure, let's discuss.",
  },
  {
    slug: 'traders-investors',
    n: '06',
    title: 'Traders & Active Investors',
    subtitle: 'Stock/F&O Traders, Crypto Traders, Real Estate Investors',
    challenge: "You have capital gains from trading, investing, or property sales. Tax treatment is complex (short-term vs. long-term rates vary). You're not sure how to compute gains correctly. ITR filing feels risky.",
    whatWeDo: 'Capital gains computation (short-term, long-term, indexation benefits), securities transaction tax (STT) and surcharge analysis, F&O tax treatment (separate from capital gains), property sale capital gains (with indexation), ITR filing with detailed schedules, advance tax planning for next year.',
    whyMojaa: 'Traders need precision. A small error in gain computation compounds into audit risk. We build detailed workings so gains are computed correctly and defensible in audit.',
    engagement: 'Annual capital gains audit + ITR filing + advance tax planning for next financial year.',
    nextStep: "If you're trading/investing actively and want tax efficiency, let's discuss.",
  },
  {
    slug: 'service-providers',
    n: '07',
    title: 'Service Providers & Consultants',
    subtitle: 'Architects, Contractors, Agencies',
    challenge: "You invoice for services. GST compliance is complex. Clients deduct TDS on your invoices. You're not sure which expenses are deductible. Cash flow is variable (projects come and go).",
    whatWeDo: 'GST registration and strategy (when to register, rate classification), TDS tracking (contractors deduct 1%, professionals deduct 10%), expense classification and deduction maximization, ITR filing as business proprietor, cash flow planning and receivables management.',
    whyMojaa: "Service businesses have unique GST and TDS treatment. We ensure you're claiming all eligible input credits and accurately reporting service income.",
    engagement: 'GST compliance (monthly/quarterly) + annual ITR filing + quarterly cash flow review. Bundled engagement based on transaction volume.',
    nextStep: "If you're providing services with GST complexity, let's discuss.",
  },
  {
    slug: 'msme-businesses',
    n: '08',
    title: 'MSME Businesses',
    subtitle: 'Artisans, Manufacturers, Exporters',
    challenge: "You're registered for MSME/Udyam. You have government contracts or bank lending needs. You need to show clean financials to government and banks. You're navigating GST, export compliance, and credit guarantee schemes.",
    whatWeDo: 'MSME/Udyam registration and compliance, statutory audit and financial statement preparation, GST reconciliation (GSTR-3B, GSTR-9), TDS compliance on government payments, export documentation and compliance, credit guarantee scheme support (financial statement certification for bank loans).',
    whyMojaa: 'MSMEs have specific compliance requirements for government contracts and bank lending. We ensure your books meet these standards.',
    engagement: 'Annual audit + monthly GST compliance + ad-hoc export/credit scheme support.',
    nextStep: "If you're MSME and need lender-ready financials, let's discuss.",
  },
  {
    slug: 'incubation-centres',
    n: '09',
    title: 'Incubation Centres & Accelerators',
    subtitle: 'Program Managers, Investor Relations',
    challenge: 'You manage a portfolio of 20–50 startups. You want them fundraise-ready. You need a systematic approach to financial compliance audits and valuation guidance. Currently, you\'re advising founders on an ad-hoc basis; you need a structured process.',
    whatWeDo: 'Portfolio startup audits (compliance, financial readiness, cap table validation), batch valuation analysis, compliance checklist standardization, founder financial literacy workshops, pre-fundraise readiness certification, due diligence support coordination.',
    whyMojaa: 'We understand incubator dynamics. We can audit startups efficiently, identify gaps, and prioritize fixes. We help your program look rigorous to limited partners and investors.',
    engagement: 'Quarterly portfolio audits + monthly founder office hours + half-yearly compliance report. Custom engagement based on portfolio size and depth needed.',
    nextStep: "If you manage a startup portfolio, let's discuss batch engagement options.",
  },
  {
    slug: 'saas-digital',
    n: '10',
    title: 'SaaS & Digital Businesses',
    subtitle: 'Sector-Specific',
    challenge: "You're B2B SaaS with international customers. Revenue recognition (when to book revenue), GST on digital services (0% export vs. 18% domestic), MRR vs. ARR tracking, unit economics (CAC, LTV, churn), and DPIIT recognition are unique to SaaS. General CAs don't understand SaaS metrics.",
    whatWeDo: 'Revenue recognition policy (ASC 606 aligned), GST structuring (export of services with zero GST), monthly SaaS MIS (MRR, ARR, churn, CAC/LTV), DPIIT recognition support, VC financial model reviews, Series A funding prep (SaaS investors want specific metrics).',
    whyMojaa: "We've built financial models for 30+ SaaS startups. We understand metrics investors care about and build MIS accordingly.",
    engagement: 'Incorporation + setup (months 1–2) → Monthly SaaS MIS → Fundraising support with modeling and due diligence prep.',
    nextStep: "If you're SaaS with ₹5L+ MRR, let's discuss.",
  },
  {
    slug: 'd2c-ecommerce',
    n: '11',
    title: 'D2C & E-Commerce',
    subtitle: 'Sector-Specific',
    challenge: "You're direct-to-consumer (selling online, social commerce, or your own website). Inventory accounting is complex. Refunds and returns affect revenue recognition. GST on different product categories (food, beauty, electronics) varies. You need working capital management for inventory.",
    whatWeDo: 'Inventory accounting and valuation, revenue recognition with returns/refunds, GST rate classification by product, working capital optimization (inventory days, payable days), marketplace accounting (Amazon, Flipkart commission structures), monthly D2C MIS (unit margins by product, inventory turnover, CAC by channel).',
    whyMojaa: 'D2C businesses are high-velocity, high-inventory. We build real-time inventory and cash management systems. Helps you decide what to stock and what to discontinue.',
    engagement: 'Monthly MIS + inventory management + quarterly working capital review.',
    nextStep: "If you're D2C with ₹50L+ annual revenue, let's discuss.",
  },
  {
    slug: 'edtech',
    n: '12',
    title: 'EdTech & Service-Based',
    subtitle: 'Sector-Specific',
    challenge: "You're selling courses, tutoring, or coaching online. Revenue is subscription-based (monthly or annual). You're managing refunds, deferred revenue (payment upfront, delivery over time), and student churn. Tax treatment of educational services has specifics.",
    whatWeDo: 'Deferred revenue accounting, subscription MIS (MRR, ARR, churn rate, cohort retention), refund policy accounting, GST on educational services (exempt or taxable depending on format), DPIIT recognition support, working capital management (you get paid first, deliver later).',
    whyMojaa: "Educational businesses have unique deferred revenue complexities. Standard accounting doesn't capture student cohort health. We build cohort-level MIS.",
    engagement: 'Monthly cohort MIS + quarterly churn analysis + annual audit.',
    nextStep: "If you're EdTech with ₹1Cr+ revenue, let's discuss.",
  },
]
