export const faqSections = [
  {
    id: 'startup-compliance',
    title: 'Startup Compliance',
    subtitle: 'Founders, Pre-Incorporation',
    faqs: [
      {
        q: 'When Should I Incorporate My Company vs. Stay as a Proprietorship?',
        who: 'Pre-incorporation founders',
        a: [
          "You should incorporate when you're serious about scaling. Timing typically hits when one of these is true: you've validated product-market fit and are ready to hire employees (incorporation is mandatory before hiring), you're approaching ₹40L–₹50L annual revenue (GST registration becomes unavoidable), or you want to raise external funding (investors only invest in Pvt Ltd or LLP companies).",
          'Staying as proprietorship makes sense only if you\'re a solo freelancer or consultant with sub-₹20L annual revenue and no plans to hire or raise capital. Once you cross ₹20L revenue or want to bring in co-founders, incorporation saves you tax headaches (proprietorship ITR gets scrutinized more closely on income-to-expense ratios).',
          'Real timeline: Most founders incorporate within 6 months of starting. The earlier you incorporate, the cleaner your historical financial records. If you\'re operating as proprietorship now and planning to incorporate later, we recommend reconstructing 6–12 months of proprietorship financials after incorporation. This creates an investor-ready narrative: "Proprietorship phase (months 1–6) validated the business model. Company phase (month 7 onwards) is where we scaled and raised capital."',
          'Cost consideration: Incorporation + first year compliance costs ₹30K–₹50K depending on complexity. Delaying means playing catch-up later with backdated filings and penalty risk. Better to incorporate early.',
          "Next step: Book a 20-minute call. We'll assess your specific situation (revenue, employee count, fundraise plans) and tell you if now is the right time or if waiting 2–3 months makes sense.",
        ],
      },
      {
        q: "What's the Difference Between Pvt Ltd, LLP, and OPC? Which Should I Choose?",
        who: 'Pre-incorporation founders, incubation centre advisors',
        a: [
          'Three structures dominate startup incorporation. Private Limited Company is the default choice for VC-fundable startups. It has unlimited members (co-founders and investors), easier fundraising mechanics, clear investor rights documentation (shareholder agreements), and strong statutory governance framework. The downside is more compliance burden (statutory audit mandatory from year 1, quarterly GST returns if registered, annual ROC filings).',
          "Limited Liability Partnership (LLP) works well if you have 2–4 equal co-founders and want flexibility. LLP has lighter statutory compliance (no mandatory audit unless turnover > ₹1 Cr), profit-sharing is flexible, and partners pay personal income tax on their share (no double taxation at company level). The limitation: investors don't like LLP structures because profit rights don't convert to equity cleanly during exit. Also, LLP can only have 99 partners maximum.",
          "One Person Company (OPC) is sole founder territory. Single member, minimal compliance, but the moment you bring in a co-founder or investor, you must convert to Pvt Ltd. OPC also can't accept external investment (only personal loans). If you're 100% solo and plan to stay that way, OPC works. The moment you want to hire a CTO or raise angel investment, you'll regret OPC.",
          'Tax difference: Pvt Ltd and OPC have identical tax treatment. LLP is taxed differently (pass-through entity). For VC-track startups, Pvt Ltd is standard.',
          'Our recommendation: If you have co-founders or plan to raise capital within 18 months, choose Pvt Ltd. If you\'re solo or have an equal partnership without capital plans, consider LLP. OPC is rare in our client base.',
          'Next step: We can model tax and structuring implications for your specific situation. Book a call to discuss.',
        ],
      },
      {
        q: 'What Is Form INC-20A and When Is It Due? What Happens If I Miss the Deadline?',
        who: 'Newly incorporated founders',
        a: [
          'Form INC-20A is the statutory declaration of commencement of business filed with the Registrar of Companies (ROC). Every company incorporated under the Companies Act must file INC-20A within 180 days of incorporation to declare that the company has begun business operations.',
          "Why it matters: INC-20A signals to the government and investors that your company is operationally live. Without INC-20A, your company technically hasn't commenced business in the eyes of law. This creates issues if you're taking client payments, filing GST returns, or approaching investors (they ask for INC-20A proof).",
          "Timeline: If you incorporated on March 15, 2026, your INC-20A deadline is September 12, 2026. That's 180 days. Miss it? The penalty is ₹50,000 on the company and ₹1,000 per day on every officer (director) in default. If you miss by 60 days, you're looking at ₹60,000 in director penalties alone. Most founders don't realize this penalty compounds daily.",
          "What we do: We track your incorporation date and flag INC-20A filing 60 days before the deadline. We prepare the declaration, gather bank certificate proof, and file with ROC. The filing fee is ₹100 (nominal). Most founders file this in the first month itself if they're organized, but we ensure you don't slip.",
          "Next step: If you incorporated in the last 6 months and haven't filed INC-20A, reach out. We can file immediately.",
        ],
      },
      {
        q: 'What Is DPIIT Recognition and Should Every Startup Apply for It?',
        who: 'Newly incorporated founders, incubation centre managers',
        a: [
          'DPIIT recognition is certification from the Department for Promotion of Industry and Internal Trade that your company is a "Startup" under government definition. Recognition unlocks tax benefits (Section 80-IAC holiday for 7 years), government procurement eligibility (GeM platform), priority lending from banks (credit guarantee schemes), and visa fast-tracking for foreign employees.',
          'Eligibility is clear: your company must be incorporated between April 1, 2016 and March 31, 2030 (so you have a 14-year window). Turnover must be below ₹100 Cr in any financial year. Your business must involve innovation, development, deployment, or commercialization of new products, processes, or services in high-tech sectors (IT, biotech, renewable energy, aerospace, etc.) or traditional sectors with significant innovation.',
          'The ₹100 Cr turnover limit is a hard ceiling. If you cross it, you lose DPIIT recognition immediately and lose all Section 80-IAC tax benefits for that year onwards. We track this monthly in your MIS to flag when you\'re at 70% of the cap so you can plan accordingly.',
          'Government fee is zero. Registration takes 5–10 working days on the startup India portal.',
          'Tax benefit: Section 80-IAC allows 100% deduction on profits for 7 years if you qualify. For a ₹50L profitable company, that\'s ₹50L tax deduction, saving ₹15L in tax annually.',
          "Who should apply? Every startup planning to raise capital. Investors specifically ask \"Are you DPIIT recognized?\" If you're not, it signals either you're not innovation-focused or you're already above ₹100 Cr (both are red flags). If you're below ₹100 Cr and haven't applied, apply immediately.",
          "Next step: Book a call. We'll assess eligibility and manage the full registration process.",
        ],
      },
      {
        q: 'What Statutory Compliance Do I Need to Handle in Year 1 After Incorporation?',
        who: 'Newly incorporated founders',
        a: [
          "Year 1 compliance after incorporation is heaviest. Here's what's mandatory.",
          'Within 30 days: Appoint your first auditor and file Form ADT-1 with ROC. Every company needs an auditor from day 1. Non-filing attracts ₹300 per day penalty.',
          'Within 60 days: Issue share certificates to all shareholders. If you incorporated with 2 co-founders, each co-founder gets a share certificate. File Form PAS-3 (allotment of shares) with ROC if there was any share allotment after incorporation.',
          "Ongoing in Year 1: Quarterly GST return filing if you're registered (GSTR-1 and GSTR-3B). Monthly TDS deduction and deposit if you're paying contractor fees or professional fees. Annual director KYC (Form DIR-3) filing before March 31.",
          'Before March 31 (end of FY): Statutory audit of your books is mandatory regardless of turnover or profit. Preparation of annual financial statements. Filing of annual ROC returns (Form AOC-4 for financial statements, Form MGT-7 for board minutes).',
          'This all sounds overwhelming, but we handle the calendar and execution. You just provide data (bank statements, invoices). We file everything on time.',
          'Biggest mistake founders make: assuming "I\'m a startup so audit is not mandatory." Wrong. Audit is mandatory for every company from year 1, regardless of size. The only exemption is if you\'re a One Person Company (OPC) with turnover below ₹1 Cr and no employees, and even then, best practice is to get audited.',
          "Next step: After incorporation, send us your incorporation documents. We'll prepare a compliance calendar for your entire FY with all due dates.",
        ],
      },
      {
        q: 'Should I Apply for MSME/Udyam Registration? What Are the Benefits?',
        who: 'Newly incorporated founders, traders, SMEs',
        a: [
          'MSME (Micro, Small, Medium Enterprise) registration on the Udyam portal offers: priority lending from banks (loans up to ₹1 Cr with government-backed credit guarantee), participation in government procurement (GeM platform preference), delayed payment protection act (if your customer delays payment by 30 days, you can claim interest), and exemption from many statutory compliances (some inspection regimes).',
          'Eligibility is based on investment in plant & machinery/equipment. Micro: below ₹1 Cr. Small: ₹1 Cr to ₹10 Cr. Medium: ₹10 Cr to ₹50 Cr.',
          'Who should register? Any startup in manufacturing, services, or trade below ₹1 Cr (micro) or ₹10 Cr (small) will benefit from MSME status. Most startups we work with are micro-MSME.',
          'Key benefit: Credit guarantee scheme. Instead of a bank demanding personal guarantees from founders, government backs the loan with guarantee. Bank is more likely to approve.',
          'One caveat: Some startups avoid MSME registration because they think it signals "small, not venture-backed." Wrong. MSME is orthogonal to funding. You can be DPIIT-recognized AND MSME-registered. These are not mutually exclusive.',
          'Filing is online on udyamregistration.gov.in. Takes 1–2 days once you provide bank details and investment breakdown.',
          "Next step: We can register you within 2 days. It's a 15-minute process if you have investment details ready.",
        ],
      },
    ],
  },
  {
    id: 'tax-planning',
    title: 'Tax Planning',
    subtitle: 'Founders, Freelancers, Service Providers',
    faqs: [
      {
        q: "Should I Take Salary or Dividend? What's the Tax Difference?",
        who: 'Profitable founder-led businesses',
        a: [
          'This is the single biggest tax decision a founder makes. The answer depends entirely on company profitability.',
          "If your company is unprofitable (burning cash), take salary. Salary is a business expense. Your company deducts ₹2L salary, paying tax at slab rates. You pay income tax on ₹2L at your personal rate (roughly 20% after deductions). Total tax is lower than taking dividend from unprofitable company (which has no profit to distribute).",
          'If your company is profitable, the math flips. Company pays corporate tax (22.55% including surcharge and cess). If you take dividend, shareholders pay dividend distribution tax (which ended in 2020, so dividends are tax-free in hands of shareholder). Total tax: 22.55% on profit, then 0% in your hands. Total: 22.55%.',
          'Alternatively, if you take salary instead, company deducts salary (no corporate tax on salary amount). You pay income tax on salary (roughly 20% after deductions and standard deduction). Total: roughly 20%.',
          'So salary looks cheaper (20% vs 22.55%), but there\'s a catch: TDS. If you take ₹2L monthly salary, your company deducts 10% TDS (₹20K per month). That money is deposited with government. You get it back in ITR refund at year-end, but it\'s cash flow negative during the year.',
          'Dividend has no TDS (post 2020 dividend distribution tax abolishment), so dividends are cleaner cash flow.',
          "Real scenario: Profitable founder making ₹1 Cr annual profit. Takes ₹50L salary. Company pays ₹50L salary (business deduction). Founder pays ₹10L TDS over the year. Year-end refund adjusts based on actual liability, since the founder's total tax is roughly ₹10L on ₹50L salary.",
          'Alternative: Founder takes ₹25L salary plus ₹25L dividend. Tax is lower overall because dividend is not taxed in hands of founder post 2020.',
          'Our recommendation: We run both scenarios (salary vs. dividend vs. mix) based on your profitability. For most profitable startups, a mix (70% salary, 30% dividend) works best. We\'ll model it specifically for you.',
          "Next step: Book a tax planning call. We'll model your personal and company tax for different salary structures.",
        ],
      },
      {
        q: 'What Is Section 80-IAC and How Much Tax Can I Save?',
        who: 'DPIIT-recognized startups',
        a: [
          'Section 80-IAC is a tax holiday that lets DPIIT-recognized startups deduct 100% of profits for 7 consecutive years. If your startup made ₹50L profit and qualifies for 80-IAC, you can deduct the entire ₹50L, paying zero corporate tax on that profit.',
          'Eligibility: Company must be Pvt Ltd or LLP (not OPC or proprietorship). Incorporated on or after April 1, 2016. DPIIT-recognized. Turnover below ₹100 Cr in the year of deduction. Must have been operating for 2 full years before claiming (so if incorporated in 2024, earliest you can claim is FY 2026-27).',
          'Seven-year clock: You get to choose which 7 years out of the 10-year DPIIT eligibility window. Most startups choose years 1–7. But if you have loss in year 1, you can skip year 1 and claim years 2–8. The clock is flexible.',
          'Real tax saving: A ₹50L profitable startup saves ₹15L annually in corporate tax (22.55% tax rate on ₹50L profit). Over 7 years, that\'s ₹1.05 Cr in tax savings. This money can be reinvested in hiring, marketing, or stored for growth.',
          "One critical trap: The moment you cross ₹100 Cr turnover in any year, you lose the benefit for that year. If you're at ₹90L turnover and planning aggressive spending, we flag it early so you don't accidentally cross ₹100L in a quarter and lose the deduction.",
          "Our role: We track your quarterly revenue in MIS. When you're at 70% of the ₹100 Cr cap, we alert you. We also manage 80-IAC compliance (you must maintain separate books, file additional forms, etc.).",
          "Next step: If you're DPIIT-recognized and profitable, let's ensure you're maximizing 80-IAC. Book a tax planning call.",
        ],
      },
      {
        q: 'When Do I Need a Statutory Tax Audit Under Section 44AB?',
        who: 'Businesses crossing ₹1 Cr turnover',
        a: [
          'Statutory tax audit under Section 44AB is mandatory if your turnover exceeds ₹1 Cr in any financial year. Turnover is defined as gross revenue before any deductions.',
          'Practical impact: If you invoiced ₹1.2 Cr to clients even if you spent ₹60L on costs, your turnover is ₹1.2 Cr. Audit is mandatory.',
          'What happens in audit: An independent CA audits your books to verify compliance with Income Tax Act. They prepare Form 3CD (audit report) which certifies that your books are accurate and compliant. You file this with your ITR.',
          'Cost of audit: Ranges from ₹15K to ₹50K depending on complexity and transaction volume. We handle the full audit engagement.',
          "Common mistakes: Founders crossing ₹1 Cr turnover often don't realize audit is due. They file ITR without audit report. Income Tax Department notices this (the form fields for audit report are blank) and sends you a notice. You then scramble to get an audit done in 2 weeks (huge rush, likely to find errors). Better to plan audit during the year.",
          "Our recommendation: When you're at ₹70L–₹80L projected turnover, let us know. We'll prepare your books for audit and schedule the audit engagement for October-November (before ITR filing deadline).",
          'Next step: If you crossed ₹1 Cr turnover this year, reach out immediately. We can complete your audit by December and get Form 3CD ready for ITR filing in January.',
        ],
      },
      {
        q: "How Should a Freelancer or Solo Professional File ITR? What's the Best Structure?",
        who: 'Freelancers, consultants, service providers',
        a: [
          'Freelancers have two structural options: stay as individual (proprietor) or incorporate as OPC/Pvt Ltd.',
          'As individual proprietor: You file ITR-3 (for business income). Income from freelancing is taxed at slab rates (5%–30% depending on total income). Standard deduction of ₹50K on business income reduces your taxable income. You can claim all business expenses (software subscriptions, equipment, co-working space). No GST unless you register voluntarily or cross ₹20L revenue.',
          'As OPC (One Person Company): You file ITR-5 (corporate return). Company income is taxed at flat 22.55% rate (which is higher than slab rates for most freelancers). But the flexibility comes: you can take salary (some of which is deductible) and dividend (which was tax-free post 2020 dividend tax abolishment reform). Also, OPC looks more professional to clients; invoices from "XYZ Private Limited" signal legitimacy more than invoices from "Anil Kumar (proprietor)."',
          'Which is better? For freelancers earning below ₹30L annually, proprietor structure is cheaper tax-wise. For freelancers earning ₹30L–₹60L, OPC might be better because 22.55% corporate tax plus optimized salary/dividend structure beats proprietor slab rates. Above ₹60L, incorporate immediately.',
          'GST consideration: Freelancers with turnover above ₹20L (except specified sectors like IT services which have ₹40L threshold) must register for GST. GST adds compliance burden but also opens input tax credit benefits.',
          "Our recommendation: If you're a high-earning freelancer (₹40L+ annually), incorporate as OPC. Below that, stay as proprietor unless you need to project professionalism (like if you're B2B consulting to corporates).",
          "Next step: Let's review your income projections. We'll model both structures and tell you which saves more tax.",
        ],
      },
      {
        q: 'How Does GST Work on Digital Services? Do I Charge GST on My SaaS Product?',
        who: 'SaaS founders, digital service providers',
        a: [
          "GST on digital services (including SaaS, software, app subscriptions) is 18%. If you're providing SaaS to Indian customers, you charge 18% GST on top of your service fee.",
          'Example: You charge ₹1,00,000 for SaaS annual subscription to an Indian B2B customer. GST is 18% on that = ₹18,000. Customer invoice total is ₹1,18,000.',
          'Exception 1: If your customer is outside India (international customer), zero GST applies. Export of services is GST-free under export promotion. You must file a separate LUT (Letter of Undertaking) to claim zero GST on international supplies.',
          'Exception 2: B2C customers (individual end users) pay GST too. A founder paying ₹999 for your SaaS pays ₹999 plus 18% GST = ₹1,179 (if you implement this in your billing).',
          'Input tax credit: You file GSTR-1 (output tax = GST you collected from customers) and GSTR-3B (reconciliation). You claim input tax credit on expenses (cloud infrastructure, employee salaries GST paid, office rent, subscriptions GST paid). If your GST collected is ₹50L and GST on inputs is ₹30L, you owe ₹20L to government.',
          "Important: If you're crossing ₹20L revenue and haven't registered for GST, do it immediately. GST registration is optional below ₹20L (₹40L for IT services), but the moment you cross, it's mandatory and late registration attracts penalties.",
          "Common mistake: Founders forget to charge GST on SaaS invoices. They invoice ₹1L but GST @ 18% is mandatory. Customer doesn't claim input credit, and founder is liable for the tax (government doesn't care that you forgot).",
          'Our role: We ensure your billing system charges GST. We file GSTR-1 and GSTR-3B monthly, tracking your ITC precisely.',
          "Next step: If you're a SaaS or digital service provider, book a call. We'll audit your GST compliance and fix any backdated gaps.",
        ],
      },
    ],
  },
  {
    id: 'fundraising',
    title: 'Fundraising',
    subtitle: 'Founders, Incubation Centres',
    faqs: [
      {
        q: 'What Documents Do Investors Ask for During Due Diligence?',
        who: 'Founders raising Series A or Seed, incubation centre advisors',
        a: [
          'Investor due diligence is systematic. They ask for a data room (digital folder) with 20+ document categories. Here\'s what investors typically want:',
          'Financial documents: Last 3 years of P&L, last 12 months bank statements, GST returns (GSTR-3B), tax audit report if applicable, 5-year financial model with assumptions, monthly MIS for last 6 months.',
          'Statutory/legal: Memorandum & Articles of Association (MOA/AOA), Board minutes (all meetings since incorporation), Statutory registers (Register of Members, Register of Directors), Annual ROC filings (Form AOC-4, MGT-7), Director KYC (Form DIR-3), All share allotment documents.',
          'Cap table & ownership: Cap table (fully diluted, showing all share classes, conversions, anti-dilution), Share certificates, Details of all investor agreements (what rights each investor has), ESOP policy and grants, Any pledged shares or liens.',
          'Customer & contracts: List of top 10 customers (revenue contribution, contract details), Key customer agreements (NDA redacted but showing terms), Vendor agreements, IP assignment agreements (who owns the tech), Employment agreements (key employees).',
          'Compliance: GST registration, TAN, DPIIT recognition (if applicable), MSME registration (if applicable), All tax filings, Any regulatory licenses/approvals.',
          'This all sounds daunting, but we maintain this data room proactively. By the time you fundraise, 80% is already prepared.',
          'Common mistake: Founders start gathering documents only after investor interest. This costs 4–6 weeks. Better to prepare during company years 1–2 so you\'re investor-ready when opportunity hits.',
          "Our role: We conduct internal due diligence for you. We identify what's missing, what's incorrect, and fix it before investors see it. We manage the data room.",
          "Next step: If you're planning to fundraise in 6–12 months, let's do a due diligence readiness audit now. Book a call.",
        ],
      },
      {
        q: 'How Do I Understand Cap Table Dilution? What Happens to My Ownership in Each Funding Round?',
        who: 'First-time founders, co-founders',
        a: [
          "Cap table (capitalization table) shows who owns what percentage of your company. It's crucial because every funding round dilutes founder ownership.",
          'Simple example: You and a co-founder start with 50-50 ownership. You raise ₹1 Cr seed round from an angel investor. That ₹1 Cr buys, say, 20% of the company. Your ownership dilutes from 50% to 40% each (80% total founder ownership, 20% investor).',
          'In Series A, you raise ₹10 Cr from a VC. That ₹10 Cr values your company (post-money valuation) at ₹50 Cr. VC gets 20% (₹10Cr/₹50Cr). Your ownership dilutes again from 40% to 32% each.',
          'Full dilution: Most cap tables show "fully diluted" ownership including ESOP pool (10% reserved for employee stock options). So even if cap table shows you own 35%, fully diluted (after all ESOP grants vest) you own 31.5%.',
          "Anti-dilution: Some investor agreements include anti-dilution clauses. If you raise at a lower valuation in Series B (down round), investors' ownership is protected to prevent their stake from diluting further. This is complex and we explain in detail.",
          'Critical cap table mistakes we see: Cap table has founder pledges not documented (looks like founder owns less than they do). CCPS from two different rounds have conflicting anti-dilution terms (creates mess in next round). ESOP pool not reserved upfront (founder discovers in Series A that founder dilution is higher than expected). Related party investments not documented (looks suspicious to investors).',
          'Our role: We build clean cap tables and model dilution across multiple funding rounds. You\'ll see: "If I raise Series A at ₹50 Cr post-money valuation, my ownership goes from 50% to 40%. If Series B is at ₹200 Cr, it goes to 30%." This clarity helps you decide if that\'s acceptable.',
          "Next step: If your cap table is unclear or messy, book a call. We'll clean it and model your dilution path through Series A and Series B.",
        ],
      },
      {
        q: 'What Is a Shareholder Agreement (SHA)? Why Do I Need One Before Taking External Investment?',
        who: 'Founders raising capital, incubation advisors',
        a: [
          'A Shareholder Agreement is a legal contract between the founder(s) and investor(s) that defines investor rights and founder obligations. Without a SHA, an investor has no contractual protection. With a SHA, investor rights are crystal clear.',
          'ROFR (Right of First Refusal): If a founder wants to sell their shares, the investor gets first dibs to buy at the same price offered to outsiders. Protects investor from dilution by unknown parties.',
          'Drag-Along: If founders (holding, say, 70% of company) agree to sell the company, they can drag along the investor (holding 30%) to sell at the same terms. Prevents minority investors from blocking exits.',
          "Anti-Dilution: If you raise a future round at a lower valuation, investor's ownership is protected (either by issuing them more shares or by converting their shares at a lower conversion price). Protects investor from down rounds.",
          'Liquidation Preference: In case of acquisition or shutdown, who gets paid first? Usually investor gets 1x their money back before founders get anything. Protects investor capital.',
          'Tag-Along: If a founder is selling their stake to a buyer, tag-along lets minority investors join the sale on the same terms. Protects investors from being left behind in founder liquidity events.',
          'Board Rights: Investor gets board seat to monitor company progress and flag risks early.',
          'Why it matters: Without a SHA, if you raise a ₹1 Cr investment and later want to do a down round (raise at lower valuation), the investor can sue you for breach. With a SHA, anti-dilution clause covers this scenario, and you can proceed.',
          'When to get it: Before taking any external investment (even angel ₹10L). Delaying SHA means the investor has no contractual rights during critical growth phase.',
          "Our role: We don't draft legal SHA (that's a lawyer's job), but we explain SHA terms to you and flag what's founder-favorable vs. investor-favorable. We help you negotiate terms.",
          "Next step: Before signing any investor term sheet, book a call. We'll review the financial terms and SHA clauses with you.",
        ],
      },
      {
        q: 'How Do I Value My Startup? What Valuation Methods Should I Use?',
        who: 'Founders preparing for fundraise',
        a: [
          'Startup valuation is part art, part science. Investors use multiple methods and average them out.',
          'Method 1: Berkus Method. Used for very early startups (pre-revenue or minimal revenue). Scores company on 5 factors (sound idea, prototype, management team, strategic relationships, sales/funding momentum), each worth ₹50L max. Total valuation = sum of scores, capped at ₹2.5 Cr. This is a rough estimate, not precise.',
          'Method 2: Scorecard Method. Investor compares your startup against other similar-stage startups. Scores you on management (30%), market (25%), product (15%), competition (10%), marketing channels (10%), funding need (5%), other (5%). Multiplies your score against average startup valuation in your category. Gives a range, not a fixed number.',
          "Method 3: VC Method. Assumes investor wants 20–40% ownership in your company for their investment. Works backwards: if investor puts ₹1 Cr and wants 30%, your post-money valuation is ₹1Cr / 0.30 = ₹3.33 Cr. This method is investor-driven.",
          "Method 4: Comparable Company Method. Looks at exits in your sector. If similar SaaS companies exited at 10x revenue multiple, and you're at ₹1 Cr revenue, your valuation is ₹10 Cr. Used for later-stage startups with clear comps.",
          'Most realistic approach: Combine methods 1–3, get 3 valuations, average them. Expect a range (₹2–₹3 Cr) not a fixed number.',
          'Common mistakes: Founders pick the highest valuation from a method without justifying it. Investors see through this. Better to show your math: "Using Berkus, we\'re at ₹2 Cr. Using Scorecard, ₹2.5 Cr. Using VC method at 25%, ₹3 Cr. Average is ₹2.5 Cr." Investors respect the rigor.',
          "Our role: We run all 4 valuation methods for you. We show the range and help you justify your target valuation to investors.",
          "Next step: If you're fundraising in next 6 months, let's model your valuation. Book a valuation call.",
        ],
      },
      {
        q: "What's the Difference Between a SAFE Note, Convertible Note, and CCPS? Which Should I Use for Angel Investment?",
        who: 'Founders raising angel rounds, incubation advisors',
        a: [
          'These are three different instruments for taking investment, each with different legal and tax implications.',
          'SAFE (Simple Agreement for Future Equity) is a lightweight agreement. Investor gives you ₹50L now. This is not debt, not equity yet. On a future funding event (Series A at ₹50 Cr valuation), the SAFE converts to equity at a discount (e.g., 20% discount means investor gets shares at 80% of Series A price). If no future funding event happens, SAFE never converts (this is rare but possible). SAFE is simple, cheap to draft, and popular in Y Combinator-style accelerators. Downside: investor has no voting rights until conversion.',
          'Convertible Note is structured like a debt instrument. Investor gives ₹50L as a "loan" with 10% annual interest. After 3 years (or on Series A, whichever is earlier), the loan converts to equity. If company shuts down before conversion, investor is creditor and recovers money before equity holders. Convertible notes have interest accrual risk (if you don\'t convert in 3 years, you owe interest payments). Less popular in India; more common in US.',
          'CCPS (Compulsorily Convertible Preference Shares) is an equity instrument from day 1. Investor gets shares (not debt), but these shares have special rights (liquidation preference, anti-dilution). CCPS must convert to ordinary equity on a future trigger (Series A, IPO, etc.). CCPS looks like equity, taxed like equity, gives investor voting rights from day 1. More complex legally.',
          'Tax implications: SAFE and Convertible Notes are tax-efficient for founders initially (no capital gains tax when they convert). CCPS triggers capital gains tax considerations at conversion. But CCPS looks cleaner on cap table.',
          "Our recommendation for angel rounds: Use CCPS. It's more familiar to Indian angels and investors, and cleaner on cap table. Avoid SAFE unless you're in an accelerator (most Indian angels don't understand SAFE yet).",
          "Next step: Before you sign any angel investment agreement, book a call. We'll review the terms and flag risks.",
        ],
      },
    ],
  },
  {
    id: 'virtual-cfo',
    title: 'Virtual CFO & Financial Operations',
    subtitle: 'Scaling Businesses, SMEs',
    faqs: [
      {
        q: "When Does a Startup Actually Need a Virtual CFO? How Do I Know If It's the Right Time?",
        who: 'Scaling startups (₹50L–₹10 Cr revenue), growing SMEs',
        a: [
          "Most founders hire a CFO when it's already too late (cash crisis, financial chaos). Better to hire fractional/virtual CFO earlier when business is predictable.",
          'Trigger 1: You\'re spending ₹2L+ per month and don\'t know cash runway down to the week. If you say "I think we have 3 months of cash," that\'s not knowledge, that\'s guessing. Virtual CFO gives you exact runway (e.g., "You have 8 weeks and 4 days").',
          "Trigger 2: You have multiple revenue streams or products and don't know which is profitable. If you invoice ₹10L/month but don't know if Product A is 60% margin and Product B is 20% margin, you need MIS clarity.",
          "Trigger 3: You're raising capital and need monthly board-ready financial reporting. You can't send a rough P&L to investors. You need dashboards, metrics, and narratives.",
          'Trigger 4: Your month-end close takes more than 10 days. If bookkeeper is scrambling 2 weeks into next month to close books, you need a CFO to systematize it.',
          "Trigger 5: You're making hiring or spending decisions without financial modeling. If you want to hire a VP Sales (₹1Cr annual cost) but don't have a model showing ROI on that hire, you need a CFO.",
          "Trigger 6: You're approaching ₹5 Cr revenue and can't do internal fundraising analysis (how much capital do I need, when do I need it, what valuation should I target). You need a CFO.",
          'Cost: Virtual CFO is ₹25K–₹75K per month depending on complexity, not the ₹80L+ for a full-time CFO. You get roughly 30 hours/month of strategic CFO time instead of 160 hours, but you get the senior expertise you need.',
          'Our approach: Monthly 1-hour review call, weekly MIS delivered by 10th of month, ad-hoc email/call support, quarterly financial projections.',
          "Next step: If you're ₹50L+ revenue with any of the above triggers, let's discuss. Book a call.",
        ],
      },
      {
        q: 'What Should Be in My Monthly MIS Report? What Metrics Matter Most?',
        who: 'Founders, business leaders wanting financial clarity',
        a: [
          'MIS (Management Information System) is your monthly financial dashboard. Most CAs send a 20-row P&L and call it done. Real MIS tells the story of your business.',
          'P&L (Profit & Loss): Revenue by product/segment, COGS, gross margin %, operating expenses by category, EBITDA, tax, net profit. Should compare to budget and last month.',
          'Cash flow: Cash collected from customers, cash spent on expenses, ending cash balance, runway (weeks of cash remaining). This is critical. A profitable company can run out of cash if customers don\'t pay.',
          'Balance sheet snapshot: Current assets, current liabilities, working capital.',
          'Key metrics: Revenue, gross margin %, CAC (customer acquisition cost), LTV (lifetime value), burn rate, churn rate, DSO (days sales outstanding, how long to collect customer payments).',
          'Customer health: Top 10 customers, concentration (do top 3 customers represent 60% of revenue?), churn rate (% of customers lost each month).',
          'Segment breakdown: If you have B2B and B2C, show each separately. If you have Product A and Product B, show profitability of each.',
          'Budget vs. actuals: Every category should compare to budget. Flag variances (e.g., "Marketing spend is 30% over budget, why?").',
          'Format: Visual, not data-heavy. Charts for revenue trend, margin trend, cash runway. Narrative at top: "Key highlights: Revenue up 15% MoM, churn rate improved to 2% (from 3%), cash runway is 18 weeks."',
          'Most common mistake: Founders conflate MIS with accounting report. Accounting report is what auditors see (compliance-focused). MIS is what founders and investors need (decision-focused).',
          'Our delivery: MIS by 10th of month, 3-page document, emailed directly to founder.',
          "Next step: If your current MIS is dull, let's redesign it. Book a call.",
        ],
      },
      {
        q: "How Do I Calculate Runway? What's a Healthy Runway for My Stage?",
        who: 'Early-stage startups, founders burning cash',
        a: [
          'Runway is how many weeks/months of cash you have left before you run out of money. Formula: Current cash balance / average monthly burn rate = runway in months.',
          'Example: You have ₹50L in bank. Monthly burn (expenses) is ₹10L. Runway = ₹50L / ₹10L = 5 months.',
          'But this assumes flat burn. Real startups have variable burn. In month 1 you spend ₹8L (low hiring), in month 2 you spend ₹12L (new team). You need to forecast next 3 months and calculate average burn.',
          "Runway benchmarks by stage: Pre-revenue, you don't have runway, you have capital. If you have ₹1 Cr cash and burn is ₹20L/month, runway is 5 months; target is to reach revenue before cash runs out.",
          'Early revenue (₹5–₹20L MRR): You should maintain 12–18 months runway. Anything less is risky. Anything more means you\'re not spending enough.',
          "Growth stage (₹20L+ MRR): Investors expect you to burn more aggressively (hiring, marketing) to scale. Maintain 9–12 months runway. If you have 24 months, you're under-investing in growth.",
          'Unit economics matter: A company with poor unit economics (CAC > LTV) is burning for a reason (losing money on customers). A company with strong unit economics (LTV 3x CAC) is burning to scale (investments expected to be profitable).',
          "Common mistake: Founders forget to factor in uneven cash collection. Invoice ₹20L to customer but they pay in 45 days. Your cash balance doesn't reflect this. Real runway is lower than balance sheet suggests.",
          'Our role: We forecast revenue, model expense timing, calculate runway weekly. When you\'re at 6-month runway, we alert you to fundraise (takes roughly 3 months to close a round).',
          "Next step: If you don't know your runway down to the week, book a call. We'll build a dynamic runway model for you.",
        ],
      },
      {
        q: 'How Should I Think About Hiring Decisions? Should I Hire Now or Wait?',
        who: 'Scaling startups, founders making first hires',
        a: [
          'Hiring decision should be financial + strategic, not emotional.',
          "Financial analysis: If you want to hire a VP Sales for ₹1Cr annual cost (salary + benefits + setup), what's the expected ROI? Will this person drive ₹5Cr incremental revenue? If yes, ROI is 5x. If no, don't hire.",
          'Expected revenue from hire = current revenue / (1 + growth target) = forecast revenue. Does VP Sales justify forecast?',
          'Runway impact: If you hire today (₹80L annual = ₹7L/month), what\'s the impact on runway? Current runway is 12 months. After hire, burn goes from ₹10L to ₹17L. New runway = current cash / ₹17L. If this goes below 9 months, you need to fundraise sooner. Can you afford to fundraise sooner (extra legal fees, management time)?',
          "Our recommendation: Don't hire based on gut feel. Model the hire. Show us the revenue justification. We'll tell you if runway allows it.",
          "Next step: Before hiring your next person, run the numbers by us. Book a hiring decision call.",
        ],
      },
      {
        q: 'What Is Working Capital Optimization? Why Does It Matter?',
        who: 'Businesses scaling, improving cash flow',
        a: [
          'Working capital is current assets minus current liabilities. High working capital means you have cash tied up in inventory or receivables. Low working capital means you convert sales to cash quickly.',
          'Example: You have ₹1 Cr inventory sitting in warehouse (current asset). You have ₹50L payable to suppliers (current liability). Working capital = ₹1Cr - ₹50L = ₹50L. That ₹50L is cash tied up and not available for operations.',
          'Working capital optimization means reducing cash tied up without hurting operations. Three levers:',
          'Inventory: If you carry 60 days of inventory but only need 30, you\'re holding ₹30L excess cash. Reduce to 40 days, free up ₹15L. Redeployed to marketing or hiring.',
          'Receivables (customer payments): If customers pay in 45 days but you can negotiate to 30 days, you reduce DSO (days sales outstanding). Free up cash cycle by 15 days.',
          'Payables (supplier payments): If you pay suppliers in 15 days but can negotiate to 30 days, you extend payment cycle. But this can hurt supplier relationships, so be careful.',
          'Real impact: A ₹10 Cr revenue business with sloppy working capital might have ₹1.5 Cr cash tied up. Optimized, it\'s ₹50L. That ₹1 Cr is freed cash for growth or runway extension.',
          'Our role: We analyze your working capital cycle. We identify where cash is stuck. We recommend specific levers to optimize.',
          "Next step: If you feel like revenue is growing but cash isn't, working capital is likely the culprit. Book a call.",
        ],
      },
    ],
  },
  {
    id: 'nri-fema',
    title: 'NRI / FEMA / International Compliance',
    subtitle: 'NRIs, HNIs, Overseas-Based Founders',
    faqs: [
      {
        q: 'What Is the Difference Between NRE, NRO, and FCNR Accounts? Which Should I Use?',
        who: 'NRIs, overseas-based founders returning to India',
        a: [
          "If you're an NRI (Non-Resident Indian), your bank accounts have tax and repatriation implications. Three types exist.",
          'NRE (Non-Resident External) Account is for foreign income only. You earn salary in US, transfer to NRE account in India. Money in NRE is fully tax-free in India (not taxable as Indian income). If you keep money in NRE, repatriation is free (you can send it back to US without tax). Interest on NRE is taxable in India but often not taxable in your NRI country due to DTAA benefits.',
          'NRO (Non-Resident Ordinary) Account is for Indian-source income. You earn rental income from property in India, receive it in NRO account. NRO income is fully taxable in India (you file Indian ITR on NRO income). Repatriation is limited to specified annual caps for savings from NRO; beyond that, you need RBI permission.',
          'FCNR (Foreign Currency Non-Resident) Account is a fixed-deposit account in foreign currency. You open FCNR in USD or EUR, deposit foreign currency directly. No repatriation limit (you can withdraw anytime), but interest is lower than regular FDs. Used mainly for savings, not transactions.',
          'Tax implication: NRE is tax-free in India, NRO is taxable, FCNR interest is taxable in India.',
          'For most NRIs: Use NRE for foreign income (salary, freelance income from foreign clients). Use NRO only if you have Indian rental income.',
          "Common mistake: NRIs deposit foreign income into NRO account thinking it's easier. Then they're taxed on the whole amount. Better to deposit into NRE (tax-free) and only bring what you need to India via NRO.",
          "Our role: We help structure your accounts for tax efficiency. We file your ITR as NRI correctly.",
          "Next step: If you're an NRI earning foreign income, book a call. We'll optimize your account structure.",
        ],
      },
      {
        q: "I'm an NRI Investing in an Indian Startup. What Are the FEMA and Tax Implications?",
        who: 'NRI angels investing in startups, HNI investors',
        a: [
          "If you're investing ₹50L in an Indian startup as an NRI, three regulations apply: FEMA, Income Tax, and Company Law.",
          'FEMA (Foreign Exchange Management Act) governs cross-border money movement. Your ₹50L investment is inward remittance of foreign funds. Your bank will file the applicable inward remittance report shortly after receiving your money, and the startup must report your investment to RBI within 30 days (failure to report triggers penalties).',
          'Key FEMA compliance: If you\'re investing in an Indian startup as equity, the startup must: declare you as a foreign investor in their annual compliance, file the FC-GPR report if capital is foreign-sourced, and maintain documents proving source of funds (bank statements showing foreign origin). These requirements are often missed by startups, creating compliance gaps.',
          'Income Tax: Your investment stake is not taxed at the time of investment. When you exit (sell your stake), you pay capital gains tax on profit. Short-term capital gains (holding < 2 years): taxed at slab rates. Long-term (holding > 2 years): taxed at 20% with indexation benefit (inflation-adjusted). NRI exit gains are taxed in India, even if you\'re exiting from abroad. DTAA (Double Taxation Avoidance Agreement) between India and your country of residence may provide relief.',
          'One exception: Angel tax was abolished on April 1, 2025. Previously, if you invested in a startup at a valuation lower than government-determined value, founder faced tax on the "discount." Abolished now, so no tax on valuation discounts.',
          "Our role: We ensure the startup you're investing in has proper FEMA compliance before you invest. We file the FC-GPR report on your behalf (in coordination with the startup). We compute capital gains tax on your eventual exit.",
          "Next step: Before investing, send us the term sheet. We'll review FEMA compliance requirements and ensure the startup can handle your investment.",
        ],
      },
      {
        q: "If I'm an NRI, Do I Need to File an Indian Income Tax Return? What Income Is Taxable in India?",
        who: 'NRIs earning Indian income',
        a: [
          "If you're an NRI (stayed outside India for more than 183 days in the financial year), you still file an ITR if you have Indian-source income. Indian-source income includes: rental income from Indian property, interest on NRO account, dividend from Indian company, capital gains from sale of Indian property or stocks.",
          "Foreign-source income (salary from US employer, freelance income from US clients) is generally not taxable in India if you're NRI, unless the income is remitted to India. If you earn ₹1 Cr in US salary but never bring it to India, you don't file ITR on it.",
          'Deadline: If you have Indian-source income, ITR filing deadline for NRI is July 31 (same as resident individuals). Late filing has penalties and interest.',
          "DTAA benefit: If you're taxed in your country of residence on worldwide income (which most countries do), you may face double taxation on Indian-source income. DTAA treaties between India and your country prevent this. For example, India-US DTAA allows you to claim tax paid to US as credit against Indian tax. We help you claim this benefit on your ITR.",
          'Non-resident status for ITR filing: If you were resident for some months and NRI for others (e.g., worked in India Jan-Mar, then moved to US Apr-Dec), you\'re "Not Ordinarily Resident" (NOR) for that year. NOR status has different tax rules, and some foreign income becomes taxable. Determining NOR status is critical and often missed.',
          'Our role: We determine your exact residency status. We file ITR correctly as NRI or NOR. We claim DTAA benefits if applicable.',
          "Next step: If you're an NRI with Indian income, book a call. We'll file your ITR before July 31.",
        ],
      },
      {
        q: "I'm Selling My House in India. What Are the Tax Implications as an NRI?",
        who: 'NRIs with Indian property',
        a: [
          'Sale of Indian property as an NRI triggers capital gains tax. Calculation depends on holding period and indexation.',
          'Short-term (holding < 2 years): Capital gain = Sale price - Purchase price. Taxed at slab rates. Example: Buy for ₹1 Cr, sell for ₹1.2 Cr, gain is ₹20L, with tax computed at applicable slab rates plus surcharge.',
          'Long-term (holding > 2 years): Capital gain = Sale price - Indexed purchase price. Indexation adjusts purchase price for inflation. Taxed at 20% + surcharge. Example: Buy for ₹1 Cr (indexed to ₹1.3 Cr after inflation), sell for ₹1.5 Cr, long-term gain is ₹20L (₹1.5Cr - ₹1.3Cr), taxed at 20%, a meaningfully lower outcome than the short-term route.',
          'Timing matters: If you\'re planning to sell in the next 12 months, consider holding for 2 years to get long-term benefit. The difference can be several lakhs in tax savings.',
          'Capital gains are computed in rupees. If you bought the property for ₹1 Cr (USD denominated) and sold for ₹1.2 Cr (USD denominated), you must convert to rupees on date of purchase and date of sale. Fluctuations in exchange rate affect taxable gain (not just property appreciation).',
          'Our role: We compute capital gains accurately, accounting for indexation and exchange rate movements. We file your ITR showing capital gains tax. We also help with NRI compliance aspects (Form 21).',
          "Next step: If you're planning property sale within 18 months, let's review tax implications. Book a call.",
        ],
      },
      {
        q: 'What Is a Form 15CA/15CB and When Do I Need It?',
        who: 'NRIs remitting money from India, businesses paying foreign entities',
        a: [
          'Form 15CA is a certificate from a chartered accountant certifying that your foreign remittance (money sent outside India) complies with Income Tax Act and FEMA. Form 15CB is a certificate saying the remittance is approved by the Income Tax Officer.',
          'When needed: If you (as NRI) want to repatriate money from NRO account (Indian-source income), you need 15CA. If you (as Indian business) are paying a foreign vendor or consultant, you need 15CA. If you (as NRI) are selling property in India and remitting proceeds outside, you need 15CA.',
          'Process: You approach a CA with all documents (ITR, bank statements, proof of income source). CA files 15CA application with ITD (Income Tax Department). ITD approves or rejects. Approval takes 2–3 weeks. Bank will not allow remittance without 15CA approval.',
          'Common mistake: Businesses pay foreign vendors without 15CA, bank blocks the payment, and business scrambles for 15CA retroactively (ITD may not issue backdated certificate). Better to get 15CA before paying.',
          'Our role: We prepare 15CA applications and coordinate with ITD. We manage the approval process (2–3 week turnaround).',
          "Next step: If you're planning remittance outside India, reach out. We'll get 15CA within 2 weeks.",
        ],
      },
    ],
  },
  {
    id: 'msme-traders',
    title: 'MSME & Trader FAQs',
    subtitle: 'Traders, Service Providers, Small Businesses',
    faqs: [
      {
        q: 'Should I Register for GST if My Turnover Is Below ₹20L? Is Voluntary Registration Worth It?',
        who: 'Traders, service providers below ₹20L turnover',
        a: [
          'GST registration is mandatory if turnover crosses ₹20L (₹40L for IT services). Below ₹20L, registration is voluntary.',
          'Should you register voluntarily? It depends on your customers.',
          "If you sell B2B (business-to-business): Your customers are likely registered for GST and need input tax credit. If you invoice them without GST, they can't claim ITC, making your services more expensive for them. Customers will demand GST invoice. Voluntary registration is worth it.",
          "If you sell B2C (business-to-consumer): Consumers don't need ITC. Invoicing without GST is fine. You avoid compliance burden. Skip registration.",
          'Tax impact: If registered, you charge 18% GST on invoice. You collect GST from customers but also claim input GST on your expenses. If you collect ₹50L GST and claim ₹30L input, you owe ₹20L to government. No tax benefit either way: if you don\'t register, you\'re not taxed and don\'t claim ITC, but you also don\'t have compliance burden.',
          'Our recommendation: If more than 50% of your customers are businesses (B2B), register voluntarily for GST. Else, skip until you cross ₹20L.',
          "Next step: Send us your customer list. We'll analyze B2B vs. B2C split and recommend.",
        ],
      },
      {
        q: 'What Are My Tax Filing Obligations as a Trader? How Do I File ITR as a Self-Employed Business?',
        who: 'Small traders, business owners',
        a: [
          'As a trader/self-employed, you file ITR-3 (if organized as proprietorship) or ITR-5 (if organized as LLP or company). Filing deadline is July 31 each year.',
          'What\'s taxable: Gross revenue (turnover) minus all legitimate business expenses. Expenses include: goods purchased for resale, rent, salaries, utilities, depreciation on equipment, conveyance, insurance, professional fees (to CA, lawyer), advertising.',
          "What's not deductible: Personal expenses, fines/penalties, entertainment expenses (with limited deduction), capital expenses (equipment usually depreciated, not fully deducted in year 1).",
          'Key compliance: Maintain books of accounts (even if simple). If turnover exceeds ₹1 Cr, statutory audit is mandatory and auditor must certify books are accurate. If turnover exceeds ₹20L, GST return must be filed quarterly.',
          "Common mistake: Traders mix personal and business expenses. Withdrawals from business for personal use are not deductible business expenses, and blending the two makes your books harder to defend in audit or during a tax notice. Keep a clean separation between business and personal accounts from day one.",
          'Our role: We maintain your books, ensure expenses are properly categorized and documented, and file your ITR (with audit report if applicable) before the deadline.',
          "Next step: If your books mix personal and business transactions, let's clean them up before the next filing cycle. Book a call.",
        ],
      },
    ],
  },
]
