export const serviceGroups = [
  {
    slug: 'core-financial',
    title: 'Core Financial Services',
    desc: 'The fundamentals every registered business needs to stay compliant, audit-ready, and on top of its books.',
  },
  {
    slug: 'growth-advisory',
    title: 'Growth & Transaction Advisory',
    desc: 'Support for the moments that define a business: fundraising, scaling, structuring, and the paperwork that comes with them.',
  },
  {
    slug: 'compliance-licensing',
    title: 'Compliance & Specialised Licensing',
    desc: 'Cross-border and sector-specific compliance handled end to end, so nothing slips through.',
  },
]

export const services = [
  {
    num: '01', group: 'core-financial', slug: 'audit-assurance',
    title: 'Audit & Assurance',
    desc: 'Statutory, tax, internal, and GST audits. Risk-focused, independent, and delivered on time.',
    tagline: 'Independent, risk-focused audits that go beyond signing off a balance sheet.',
    forWho: 'Private limited companies, LLPs, and any business that needs a statutory, tax, or lender-mandated audit.',
    pointsLabel: 'Types of Audit Services',
    points: [
      { t: 'Statutory Audit', d: 'Financial statement audits under the Companies Act, conducted independently and delivered before your filing deadlines.' },
      { t: 'Tax Audit', d: 'Section 44AB tax audits with proper documentation and reconciliation against your books.' },
      { t: 'GST Audit & Reconciliation', d: 'GSTR reconciliation, input tax credit verification, and audit support during GST assessments.' },
      { t: 'Internal Audit', d: 'Process and control reviews that catch leakages and compliance gaps before a statutory auditor or regulator does.' },
      { t: 'Concurrent Audits', d: 'Ongoing transaction-level review for businesses that need real-time assurance, not just a year-end sign-off.' },
      { t: 'Inventory & Stock Audits', d: 'Physical verification and valuation audits for businesses carrying stock, including bank-mandated stock audits.' },
    ],
    advisoryLabel: 'Assurance Advisory Services',
    advisory: [
      { t: 'Internal Financial Controls (ICFR)', d: 'Testing and reporting on the controls behind your financial statements, to the standard lenders and boards expect.' },
      { t: 'Ind-AS / IFRS Compliance Advisory', d: 'Bringing financial reporting in line with Ind-AS or IFRS for consolidation, cross-border reporting, or investor requirements.' },
      { t: 'Forensic Audits & Fraud Investigation', d: 'Investigating suspected fraud or financial irregularity, with findings documented to hold up to scrutiny.' },
    ],
    edgeLabel: 'Audit & Assurance Edge',
    edge: [
      { t: 'Risk-Based Methodology', p: 'We scope every audit around where the real risk sits in your business, not a generic checklist run on autopilot.' },
      { t: 'Findings You Can Act On', p: 'Every finding is explained in plain language and paired with a fix, not just filed away in a report.' },
      { t: 'One Team, No Handoffs', p: 'The same team that audits you also handles your tax and compliance, so findings turn into action instead of getting lost between firms.' },
    ],
  },
  {
    num: '02', group: 'core-financial', slug: 'taxation',
    title: 'Direct & Indirect Taxation',
    desc: 'ITR filing, tax planning, capital gains, advance tax, GST registration and returns, NRI taxation, DTAA, and assessment representation.',
    tagline: 'Tax planning and filing that treats compliance as the floor, not the ceiling.',
    forWho: 'Founders, professionals, traders, freelancers, and NRIs who want tax handled proactively, not just filed once a year.',
    pointsLabel: 'Types of Tax Services',
    points: [
      { t: 'Direct Tax Planning & Advisory', d: 'Corporate and individual tax planning built around your business model, not deductions collected in March.' },
      { t: 'Capital Gains & Advance Tax', d: 'Correct computation and timely advance tax to avoid interest and penalty exposure.' },
      { t: 'GST Registration, Returns & Advisory', d: 'Registration, monthly/quarterly filing, and advisory on how GST applies to your specific business model.' },
      { t: 'NRI Taxation & DTAA', d: 'Residency-based tax positions and Double Taxation Avoidance Agreement relief for cross-border income.' },
      { t: 'GST Compliance Outsourcing', d: 'Ongoing GST reporting and reconciliation managed for you, month after month.' },
    ],
    advisoryLabel: 'Tax Advisory & Litigation Services',
    advisory: [
      { t: 'Transfer Pricing & Cross-Border Transactions', d: 'Pricing and documentation for inter-company transactions that stands up to scrutiny.' },
      { t: 'Tax Assessment & Litigation Representation', d: 'Representing you before income tax and GST authorities through assessments, search and seizure, and appellate proceedings.' },
    ],
    edgeLabel: 'Taxation Edge',
    edge: [
      { t: 'Planned, Not Just Filed', p: 'Positions are planned through the year so filing is a formality, not a scramble against the deadline.' },
      { t: 'Direct & Indirect Under One Roof', p: 'Income tax and GST handled by the same team, so nothing falls through the crack between the two.' },
      { t: 'Representation When It Matters', p: "If a notice or assessment lands, we represent you. We don't just hand you a file and disappear." },
    ],
  },
  {
    num: '03', group: 'growth-advisory', slug: 'startup-transaction-advisory',
    title: 'Startup & Transaction Advisory',
    desc: 'Incorporation, DPIIT recognition, MSME registration, financial projections, fundraise readiness, and ESOP structuring.',
    tagline: 'Structure decides your tax and liability position for years, so we get it right from day one.',
    forWho: 'Founders from idea stage through incorporation, fundraising, and exit.',
    pointsLabel: 'Startup Advisory Services',
    points: [
      { t: 'Incorporation & Structuring', d: 'Entity choice and structuring decided around your funding and liability needs, not a template.' },
      { t: 'DPIIT & MSME Recognition', d: 'Startup India recognition and MSME/Udyam registration handled end to end.' },
      { t: 'Financial Projections', d: 'Investor-ready projections grounded in real unit economics, not optimism.' },
      { t: 'Fundraise Readiness', d: 'Getting your financials, cap table, and documentation in order before you start investor conversations.' },
      { t: 'ESOP Structuring', d: 'Employee stock option pools structured and documented correctly from the start.' },
    ],
    advisoryLabel: 'Transaction Advisory Services',
    advisory: [
      { t: 'Deal Strategy & Structuring', d: "Working through how a fundraise, acquisition, or investment should be structured before you're in a negotiation." },
      { t: 'Exit Planning', d: 'Structuring a minority sale, majority sale, full exit, or IPO route around what founders and investors actually need.' },
      { t: 'Overseas Investment Advisory', d: 'Structuring guidance for outbound or inbound cross-border investment.' },
    ],
    edgeLabel: 'Startup & Transaction Advisory Edge',
    edge: [
      { t: 'Built For Founders, Not Just Filings', p: 'We speak the language of unit economics, cap tables, and investor decks, not just balance sheets.' },
      { t: 'Involved Before Incorporation', p: "Structure decides your tax and liability position for years, so we're often in the conversation before you register anything." },
      { t: 'A Capital Markets Lens', p: "An investment banking background on the team brings deal experience most compliance-first firms don't have." },
    ],
  },
  {
    num: '04', group: 'growth-advisory', slug: 'due-diligence-valuation',
    title: 'Due Diligence & Valuation',
    desc: 'Buy-side and sell-side financial due diligence, business valuation, share valuation under Income Tax and FEMA.',
    tagline: 'The numbers behind a deal, verified and defensible before anyone signs anything.',
    forWho: 'Businesses raising capital, acquiring another company, or being acquired.',
    pointsLabel: 'Due Diligence Services',
    points: [
      { t: 'Buy-Side Due Diligence', d: 'Financial verification of a target business before you commit capital.' },
      { t: 'Sell-Side Due Diligence', d: "Getting your own financials in order and defensible before a buyer's diligence team arrives." },
      { t: 'Data Room Preparation', d: "Organising financial documentation so diligence moves faster and doesn't stall a deal." },
    ],
    advisoryLabel: 'Valuation Services',
    advisory: [
      { t: 'Business Valuation', d: 'Valuation for fundraising, M&A, or internal decision-making, using methods appropriate to your stage.' },
      { t: 'Share Valuation (Income Tax / FEMA)', d: 'Statutory valuations required for share issuance, transfer, or cross-border investment.' },
    ],
    edgeLabel: 'Due Diligence & Valuation Edge',
    edge: [
      { t: 'Numbers That Survive Scrutiny', p: "Valuations and diligence findings built to hold up under an investor's or acquirer's own review." },
      { t: 'Both Sides of the Table', p: "Buy-side and sell-side experience means we know what the other party's diligence team is actually looking for." },
      { t: 'Fast, Without Cutting Corners', p: 'A structured data room and process that keeps a deal moving instead of stalling in diligence.' },
    ],
  },
  {
    num: '05', group: 'growth-advisory', href: '/virtual-cfo',
    title: 'Virtual CFO Services',
    desc: 'MIS reporting, cash flow management, budgeting, board deck support, working capital optimization, and financial controls.',
  },
  {
    num: '06', group: 'compliance-licensing', href: '/nri-fema',
    title: 'FEMA & NRI Compliance',
    desc: 'FDI/ODI compliance, FC-GPR, DTAA advisory, transfer pricing, cross-border structuring, and NRI taxation.',
  },
  {
    num: '07', group: 'core-financial', slug: 'roc-compliance',
    title: 'Corporate Secretarial & ROC Compliance',
    desc: 'Annual ROC filings, director KYC, share allotment, change of directors, registered office changes, statutory registers.',
    tagline: 'The recurring filings every registered company owes the Registrar, handled on a calendar so nothing is missed.',
    forWho: 'Every private limited company and LLP, every year, without exception.',
    pointsLabel: 'ROC Filing Services',
    points: [
      { t: 'Annual ROC Filings', d: 'AOC-4, MGT-7, and other annual returns filed accurately and on time.' },
      { t: 'Director KYC', d: 'DIR-3 KYC and related director compliance handled before deadlines lapse.' },
      { t: 'Share Allotment & Transfer', d: 'Documentation and filings for issuing or transferring shares.' },
      { t: 'Change of Directors', d: 'Appointments, resignations, and related ROC filings managed correctly.' },
    ],
    advisoryLabel: 'Corporate Secretarial Advisory',
    advisory: [
      { t: 'Registered Office Changes', d: 'Filings and compliance when your registered office moves.' },
      { t: 'Statutory Registers', d: 'Maintaining the registers every company is legally required to keep.' },
    ],
    edgeLabel: 'Corporate Secretarial Edge',
    edge: [
      { t: 'On a Calendar, Not a Scramble', p: 'Every filing is tracked against its deadline so nothing lapses silently.' },
      { t: 'One Team, Full Picture', p: 'The same team handling your ROC compliance also sees your tax and accounts, so filings stay consistent with your actual financials.' },
      { t: 'Direct Partner Oversight', p: 'Filings reviewed by a partner, not left entirely to a junior.' },
    ],
  },
  {
    num: '08', group: 'core-financial', slug: 'bookkeeping-accounting',
    title: 'Bookkeeping & Offshore Accounting',
    desc: 'Tally, Zoho Books, QuickBooks, Xero. Monthly close, financial statement preparation, and offshore accounting for international clients.',
    tagline: 'Books closed every month, not reconstructed once a year under deadline pressure.',
    forWho: 'Any business that needs clean, current books, including international clients needing offshore accounting.',
    pointsLabel: 'Bookkeeping Services',
    points: [
      { t: 'Monthly Book Close', d: 'A closed, reconciled set of books every month, not a year-end scramble.' },
      { t: 'Financial Statement Preparation', d: 'P&L, balance sheet, and cash flow statements ready for lenders, investors, or your own review.' },
      { t: 'Bank & Vendor Reconciliation', d: 'Regular reconciliation so your books match reality, not just your assumptions.' },
    ],
    advisoryLabel: 'Offshore & Platform Support',
    advisory: [
      { t: 'Multi-Platform Setup', d: 'Tally, Zoho Books, QuickBooks, and Xero: set up and maintained on the platform you already use.' },
      { t: 'Offshore Accounting', d: 'Accounting support for international clients working across time zones and currencies.' },
    ],
    edgeLabel: 'Bookkeeping Edge',
    edge: [
      { t: 'Closed Every Month', p: 'Books closed and reconciled monthly, so you always know where the business stands.' },
      { t: 'On Your Platform', p: "We work inside the accounting software you already use, not one we force on you." },
      { t: 'Books That Feed Everything Else', p: 'Clean books are the foundation for your tax filings, audits, and Virtual CFO reporting, all handled by the same team.' },
    ],
  },
  {
    num: '09', group: 'core-financial', slug: 'corporate-restructuring',
    title: 'Corporate Restructuring',
    desc: 'Mergers, demergers, conversions, and entity restructuring aligned with tax and regulatory requirements.',
    tagline: "Restructuring that's planned around tax and regulatory consequences, not just legal form.",
    forWho: 'Businesses reorganising, consolidating, or converting entity type.',
    pointsLabel: 'Restructuring Services',
    points: [
      { t: 'Mergers & Demergers', d: 'Structuring and executing mergers or demergers with the tax implications mapped upfront.' },
      { t: 'Entity Conversion', d: 'Converting between entity types (for example, LLP to private limited) as the business outgrows its original structure.' },
      { t: 'Group Restructuring', d: 'Reorganising multi-entity groups for tax efficiency and operational clarity.' },
    ],
    advisoryLabel: 'Restructuring Advisory',
    advisory: [
      { t: 'Tax-Aligned Structuring', d: 'Evaluating restructuring options against their tax consequences before you commit to one.' },
      { t: 'Regulatory Filings', d: 'The ROC, tax, and regulatory filings that accompany any restructuring.' },
    ],
    edgeLabel: 'Corporate Restructuring Edge',
    edge: [
      { t: 'Tax Consequences Mapped First', p: 'Every restructuring option evaluated for its tax and regulatory impact before you commit to a structure.' },
      { t: 'Execution, Not Just Advice', p: 'We handle the ROC and regulatory filings that make a restructuring legally effective, not just the recommendation.' },
      { t: 'Continuity Through the Transition', p: 'The same team stays involved through compliance after the restructuring, so nothing gets dropped in the handover.' },
    ],
  },
  {
    num: '10', group: 'growth-advisory', slug: 'sha-founder-agreements',
    title: 'SHA & Founder Agreement Drafting',
    desc: 'Founder equity splits, vesting terms, exit clauses, and shareholder rights documented before disputes start.',
    tagline: "The agreement that prevents the argument, drafted before there's anything to argue about.",
    forWho: 'Co-founders setting up, or revisiting, their equity and governance arrangement.',
    pointsLabel: 'Founder Agreement Services',
    points: [
      { t: 'Founder Equity Splits', d: 'Working through equity allocation with the financial and tax consequences made explicit.' },
      { t: 'Vesting Terms', d: "Vesting schedules and cliff structures that protect the business if a founder leaves early." },
      { t: 'Exit Clauses', d: "Buyout, drag-along, and tag-along terms defined before they're ever needed." },
    ],
    advisoryLabel: 'Shareholder Advisory',
    advisory: [
      { t: 'Shareholder Rights & Protective Provisions', d: 'Voting rights, information rights, and protective provisions documented clearly.' },
    ],
    edgeLabel: 'Founder Agreement Edge',
    edge: [
      { t: 'Financial Consequences Made Explicit', p: 'Equity and vesting terms drafted with the tax and financial consequences spelled out, not left implicit.' },
      { t: 'Before the Dispute, Not After', p: 'We work with founders early, while relationships are still good and terms can be discussed calmly.' },
      { t: 'Coordinated With Your Legal Counsel', p: 'We handle the financial and structuring side, working alongside your lawyer on the legal drafting.' },
    ],
  },
  {
    num: '11', group: 'growth-advisory', slug: 'investment-documentation',
    title: 'Term Sheet & Investment Documentation',
    desc: 'Reviewing term sheets and preparing investment documentation from the finance and compliance side.',
    tagline: "A finance and compliance read on your term sheet, before you sign something you'll live with for years.",
    forWho: 'Founders closing an investment round with an angel, VC, or institutional investor.',
    pointsLabel: 'Investment Documentation Services',
    points: [
      { t: 'Term Sheet Review', d: 'Reviewing valuation, liquidation preference, and control terms from a financial and tax standpoint.' },
      { t: 'Investment Documentation', d: "Preparing the financial documentation an investor's diligence team will need." },
    ],
    advisoryLabel: 'Closing Advisory',
    advisory: [
      { t: 'Cap Table Review', d: "Making sure the round doesn't create cap table problems that surface at the next raise." },
      { t: 'FEMA & Closing Compliance', d: 'FC-GPR filings and other closing compliance for the round, coordinated alongside your legal counsel.' },
    ],
    edgeLabel: 'Investment Documentation Edge',
    edge: [
      { t: 'A Finance Read, Not Just a Legal One', p: 'We review valuation, liquidation preference, and control terms for what they mean financially, not just legally.' },
      { t: 'Cap Table Discipline', p: "We check that this round doesn't create a problem that surfaces at your next raise." },
      { t: 'A Coordinated Close', p: 'FEMA filings and closing compliance handled alongside your legal counsel so the round actually closes on time.' },
    ],
  },
  {
    num: '12', group: 'growth-advisory', slug: 'bank-loans-msme-funding',
    title: 'Bank Loans & MSME Funding Support',
    desc: 'Project reports, CMA data, and loan documentation for bank loans and MSME funding.',
    tagline: "The documentation that gets a loan application approved instead of stuck in review.",
    forWho: 'MSMEs and businesses applying for a bank loan, credit line, or working capital facility.',
    pointsLabel: 'Loan Documentation Services',
    points: [
      { t: 'CMA Data Preparation', d: 'Credit Monitoring Arrangement data prepared the way banks expect to see it.' },
      { t: 'Project Reports', d: 'Detailed project reports for term loans and new business financing.' },
      { t: 'Working Capital Analysis', d: "Analysis that supports the working capital limit you're actually asking for." },
    ],
    advisoryLabel: 'Funding Advisory',
    advisory: [
      { t: 'Bank Liaison Support', d: 'Coordinating with the bank through submission, queries, and sanction.' },
    ],
    edgeLabel: 'Funding Support Edge',
    edge: [
      { t: 'Built the Way Banks Expect', p: 'CMA data and project reports formatted the way credit teams actually review them.' },
      { t: 'Realistic Numbers', p: 'Working capital and projections grounded in your real operating cycle, not inflated to impress a bank.' },
      { t: 'We Follow Through', p: 'Support continues through submission, queries, and sanction, not just handing over a report.' },
    ],
  },
  {
    num: '13', group: 'growth-advisory', slug: 'government-grants-schemes',
    title: 'Government Grants & Scheme Assistance',
    desc: 'Startup India recognition, MSME schemes, and subsidy applications.',
    tagline: "Government support that's actually available to you, applied for correctly.",
    forWho: "Startups and MSMEs eligible for recognition, subsidies, or scheme benefits they haven't claimed yet.",
    pointsLabel: 'Scheme Application Services',
    points: [
      { t: 'Startup India Recognition', d: 'DPIIT recognition applications and the compliance that comes with maintaining it.' },
      { t: 'MSME Scheme Applications', d: 'Identifying and applying for MSME schemes your business actually qualifies for.' },
      { t: 'Subsidy Applications', d: 'Preparing and submitting subsidy applications with the supporting documentation intact.' },
    ],
    advisoryLabel: 'Eligibility Advisory',
    advisory: [
      { t: 'Eligibility Assessment', d: 'A straight assessment of what you qualify for before you spend time applying.' },
    ],
    edgeLabel: 'Government Schemes Edge',
    edge: [
      { t: 'We Check Eligibility First', p: "A straight assessment of what you qualify for before you spend time applying for something you won't get." },
      { t: "Documentation That Doesn't Bounce Back", p: 'Applications prepared with the supporting documentation schemes actually ask for.' },
      { t: 'Ongoing Compliance Included', p: 'We track the compliance that comes with maintaining recognition, not just the initial application.' },
    ],
  },
  {
    num: '14', group: 'compliance-licensing', slug: 'spice-board-certification',
    title: 'Spice Board Certification',
    desc: 'CRES and related registrations for spice exporters and processors.',
    tagline: "Export-ready certification handled so it doesn't hold up a shipment.",
    forWho: 'Spice exporters and processors needing Spices Board registration and compliance.',
    pointsLabel: 'Certification Services',
    points: [
      { t: 'CRES Registration', d: 'Certificate of Registration as Exporter of Spices, applied for and tracked to completion.' },
      { t: 'Spice Board Licensing', d: 'The licensing and renewals required to stay export-compliant.' },
    ],
    advisoryLabel: 'Export Compliance',
    advisory: [
      { t: 'Export Documentation', d: 'Supporting documentation aligned with Spices Board and export requirements.' },
      { t: 'Renewal Tracking', d: 'Keeping certifications current so they never lapse mid-shipment.' },
    ],
    edgeLabel: 'Spice Board Edge',
    edge: [
      { t: 'Sector-Specific Experience', p: "Handled for spice exporters and processors who can't afford a shipment held up over paperwork." },
      { t: 'Renewals Tracked Proactively', p: 'Certification expiry tracked so it never lapses mid-shipment.' },
      { t: 'One Team for Compliance and Tax', p: 'The same team handling your Spice Board compliance also handles your GST and export-related tax positions.' },
    ],
  },
  {
    num: '15', group: 'compliance-licensing', slug: 'fssai-registration',
    title: 'FSSAI Registration & Licensing',
    desc: 'Registration and licensing support for food and beverage businesses.',
    tagline: 'The food safety license your business needs, matched to the right category the first time.',
    forWho: 'Food and beverage businesses that need FSSAI registration or licensing to legally operate.',
    pointsLabel: 'Licensing Services',
    points: [
      { t: 'FSSAI Basic Registration', d: 'Registration for small food businesses below the threshold requiring a full license.' },
      { t: 'State & Central Licensing', d: 'Licensing at the correct tier based on your scale and operations.' },
    ],
    advisoryLabel: 'Compliance Support',
    advisory: [
      { t: 'Renewal Filing', d: 'Timely renewal so your licence never lapses and interrupts operations.' },
      { t: 'Compliance Documentation', d: 'The supporting documentation FSSAI expects, prepared correctly the first time.' },
    ],
    edgeLabel: 'FSSAI Edge',
    edge: [
      { t: 'Matched to the Right Category', p: "Registration or licensing tier matched correctly to your scale, so you're not over- or under-licensed." },
      { t: "Renewed Before It Lapses", p: 'Renewal filings tracked so your license never interrupts operations.' },
      { t: 'Bundled With Your Other Compliance', p: 'FSSAI sits alongside your GST, ROC, and tax compliance under one team instead of a separate consultant.' },
    ],
  },
]
